jdemetra/jdemetra-core

jtstoolkit/src/main/java/ec/satoolkit/seats/SeatsSpecification.java

Parameters checked: EPSPHI, RMOD, XL

Checks on some parameters of Seats specification

---

jtstoolkit/src/main/java/ec/satoolkit/seats/DefaultModelApproximator.java
jtstoolkit/src/main/java/ec/satoolkit/seats/DefaultModelApproximator2.java
jtstoolkit/src/main/java/ec/satoolkit/seats/DefaultModelApproximator3.java
jtstoolkit/src/main/java/ec/satoolkit/seats/package-info.java
jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/tramo/package-info.java
jtstoolkit/src/main/java/ec/tstoolkit/ucarima/estimation/BurmanEstimates.java
jtstoolkit/src/main/java/ec/tstoolkit/ucarima/estimation/BurmanEstimatesC.java
jtstoolkit/src/main/java/ec/tstoolkit/ucarima/estimation/McElroyEstimates.java

References to the original Tramo-Seats

Release 2.0.0

---

README.md
jtss/src/main/java/ec/tss/disaggregation/documents/DentonSpecification.java
jtss/src/main/java/ec/tss/disaggregation/documents/DisaggregationResults.java
jtss/src/main/java/ec/tss/disaggregation/documents/DisaggregationSpecification.java
jtss/src/main/java/ec/tss/disaggregation/processors/CholetteProcessor.java
jtss/src/main/java/ec/tss/disaggregation/processors/DentonProcessor.java
jtss/src/main/java/ec/tss/disaggregation/processors/DisaggregationProcessor.java
jtss/src/main/java/ec/tss/documents/MultiTsDocument.java
jtstoolkit/src/main/java/ec/benchmarking/DisaggregationModel.java
jtstoolkit/src/main/java/ec/benchmarking/denton/DentonMethod.java
jtstoolkit/src/main/java/ec/benchmarking/simplets/TsDisaggregation.java
jtstoolkit/src/main/java/ec/tstoolkit/ssf/AbstractTimeVaryingRegSsf.java
jtstoolkit/src/main/java/ec/tstoolkit/ssf/DefaultTimeVaryingRegSsf.java
jtstoolkit/src/main/java/ec/tstoolkit/ssf/RegSsf.java
jtstoolkit/src/main/java/ec/tstoolkit/ssf/TimeVaryingRegSsf.java
jtstoolkit/src/main/java/ec/tstoolkit/ssf/arima/SsfRw.java
jtstoolkit/src/main/java/ec/tstoolkit/ssf/arima/SsfRwAr1.java
jtstoolkit/src/test/java/ec/tstoolkit/ssf/TimeVaryingRegSsfTest.java

The corrections/improvements/new features have no impact on the SA algorithms

Improvement in benchmarking. Time varying regression models

---

jtss/src/main/java/ec/tss/html/implementation/HtmlSeasonalityDiagnostics.java
jtss/src/main/java/ec/tss/xml/algorithm/XmlMultiTsProcessing.java
jtss/src/main/java/ec/tss/xml/algorithm/XmlTsProcessing.java
jtss/src/main/java/ec/tss/xml/arima/XmlUcArima.java
jtstoolkit/src/main/java/ec/satoolkit/diagnostics/PeriodogramTest.java
jtstoolkit/src/main/java/ec/satoolkit/diagnostics/QSTest.java
jtstoolkit/src/main/java/ec/satoolkit/tramoseats/TramoSeatsSpecification.java
jtstoolkit/src/main/java/ec/tstoolkit/algorithm/AbstractProcResults.java
jtstoolkit/src/main/java/ec/tstoolkit/data/Periodogram.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/special/DirichletKernel.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/special/IRealFunction.java
jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/tramo/SeasonalityTests.java
jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/tramo/TramoSpecification.java
jtstoolkit/src/main/java/ec/tstoolkit/sarima/SarimaModel.java
jtstoolkit/src/test/java/ec/satoolkit/diagnostics/FTestTest.java
jtstoolkit/src/test/java/ec/satoolkit/diagnostics/PeriodogramTestTest.java
jtstoolkit/src/test/java/ec/tstoolkit/maths/special/DirichletKernelTest.java
jtstoolkit/src/test/java/ec/tstoolkit/timeseries/regression/SeasonalDummiesTest.java

Corrections in seasonality tests.
A few other small improvements

Seasonality tests

---

jtss/src/main/java/ec/tss/tsproviders/utils/MultiLineNameUtil.java
jtstoolkit/src/test/java/ec/satoolkit/diagnostics/PeriodogramTestTest.java
spreadsheetprovider/src/main/java/ec/tss/tsproviders/spreadsheet/SpreadSheetProvider.java
spreadsheetprovider/src/main/java/ec/tss/tsproviders/spreadsheet/engine/SpreadSheetParser.java

Modified PeriodogramTestTest to be ignored.

Moved support of multi-line strings into jtss.

---

jtss/src/main/java/ec/tss/sa/diagnostics/CoherenceDiagnostics.java
jtstoolkit/src/main/java/ec/satoolkit/DefaultPreprocessingFilter.java
jtstoolkit/src/main/java/ec/satoolkit/GenericSaProcessingFactory.java
jtstoolkit/src/main/java/ec/satoolkit/x11/DefaultPreprocessor.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/matrices/Householder.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/matrices/HouseholderReflection.java
jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/PreprocessingModel.java

The software handles now completely special user-defined variables in SA routines

User-defined variables in JD+ and in X12

---

jtstoolkit/src/main/java/ec/tstoolkit/arima/special/mixedfrequencies/MixedFrequenciesMonitor.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/matrices/ElementaryTransformations.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/matrices/HyperbolicRotation.java
jtstoolkit/src/main/java/ec/tstoolkit/ssf/DiffuseSquareRootInitializer.java
jtstoolkit/src/main/java/ec/tstoolkit/ucarima/estimation/McElroyEstimates.java
jtstoolkit/src/test/java/ec/tstoolkit/maths/matrices/ElementaryTransformationsTest.java

The improved initialization (faster, more stable) may have an impact on some tricky benchmarking problems

Diffuse initialization of state space models

---

jtss/src/main/java/ec/tss/sa/diagnostics/OutOfSampleDiagnosticsConfiguration.java
jtss/src/main/java/ec/tss/sa/diagnostics/OutOfSampleDiagnosticsFactory.java

* OutOfSampleDiagnosticsConfiguration.java : method check() corrected
* OutOfSampleDiagnosticsFactory.java : getName() and getDescription() corrected

Fix: OutOfSampleDiagnostics

---

jtss/src/main/java/ec/tss/xml/calendar/XmlNationalCalendar.java
jtss/src/main/java/ec/tss/xml/calendar/XmlSpecialCalendarDay.java
jtstoolkit/src/main/java/ec/tstoolkit/timeseries/calendars/EasterRelatedDay.java
jtstoolkit/src/main/java/ec/tstoolkit/timeseries/calendars/NationalCalendarProvider.java
jtstoolkit/src/main/java/ec/tstoolkit/timeseries/calendars/SpecialCalendarDay.java
jtstoolkit/src/test/java/ec/tstoolkit/timeseries/calendars/EasterRelatedDayTest.java

Serialize/deserialize Julian calendar in Workspace xml file

Julian calendar value in Workspace save

---

jtstoolkit/src/main/java/ec/satoolkit/x11/DefaultPreprocessor.java
jtstoolkit/src/main/java/ec/satoolkit/x11/IX11Toolkit.java
jtstoolkit/src/main/java/ec/satoolkit/x11/X11Context.java
jtstoolkit/src/main/java/ec/satoolkit/x11/X11Kernel.java
jtstoolkit/src/main/java/ec/satoolkit/x11/X11Toolkit.java
jtstoolkit/src/main/java/ec/satoolkit/x13/X11Decomposer.java

Adding A9, A9sa, A9u and correcting D11

---

spreadsheet/spreadsheet-poi/src/main/java/ec/util/spreadsheet/poi/ExcelBookFactory.java
spreadsheetprovider/src/main/java/ec/tss/sa/output/SpreadsheetOutput.java
spreadsheetprovider/src/main/java/ec/tss/sa/output/XSSFHelper.java

Fixed OutOfMemoryError when exporting lots of TS to an Excel file.

---

jtstoolkit/src/main/java/ec/satoolkit/seats/DefaultModelDecomposer.java
jtstoolkit/src/main/java/ec/satoolkit/seats/SeatsSpecification.java
jtstoolkit/src/main/java/ec/satoolkit/seats/SeatsToolkit.java
jtstoolkit/src/main/java/ec/tstoolkit/arima/Spectrum.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/realfunctions/GridSearch.java
jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/tramo/SeasonalityTests.java
jtstoolkit/src/main/java/ec/tstoolkit/ucarima/TrendCycleSelector.java
jtstoolkit/src/main/java/ec/tstoolkit/ucarima/UcarimaModel.java
jtstoolkit/src/test/java/ec/tstoolkit/arima/SpectrumTest.java

Update of the algorithms (Tramo-Seats) for release 2.1

Release 2.1.0

---

jtstoolkit/src/main/java/ec/satoolkit/x11/DefaultExtremeValuesCorrector.java
jtstoolkit/src/main/java/ec/satoolkit/x11/X11Kernel.java
jtstoolkit/src/test/java/ec/satoolkit/diagnostics/CochranTestTest.java
jtstoolkit/src/test/java/ec/satoolkit/x13/X13SpecExcludefcastTest.java

On the right branch this time.

Fix for excludeforcast

---

odbcprovider/pom.xml
odbcprovider/src/main/java/adodb/wsh/AdoConnection.java
odbcprovider/src/main/java/adodb/wsh/AdoContext.java
odbcprovider/src/main/java/adodb/wsh/AdoDatabaseMetaData.java
odbcprovider/src/main/java/adodb/wsh/AdoDriver.java
odbcprovider/src/main/java/adodb/wsh/AdoPreparedStatement.java
odbcprovider/src/main/java/adodb/wsh/AdoResultSet.java
odbcprovider/src/main/java/adodb/wsh/AdoResultSetMetaData.java
odbcprovider/src/main/java/adodb/wsh/AdoStatement.java
odbcprovider/src/main/java/adodb/wsh/CScript.java
odbcprovider/src/main/java/adodb/wsh/PropertyLoader.java
odbcprovider/src/main/java/adodb/wsh/TsvReader.java
odbcprovider/src/main/java/adodb/wsh/Wsh.java
odbcprovider/src/main/resources/adodb/wsh/DbProperties.vbs
odbcprovider/src/main/resources/adodb/wsh/OpenSchema.vbs
odbcprovider/src/main/resources/adodb/wsh/PreparedStatement.vbs
odbcprovider/src/test/java/adodb/wsh/AdoConnectionTest.java
odbcprovider/src/test/java/adodb/wsh/AdoContextTest.java
odbcprovider/src/test/java/adodb/wsh/AdoDatabaseMetaDataTest.java
odbcprovider/src/test/java/adodb/wsh/AdoResultSetMetaDataTest.java
odbcprovider/src/test/java/adodb/wsh/PropertyLoaderTest.java
odbcprovider/src/test/java/adodb/wsh/WshTest.java
odbcprovider/src/test/resources/adodb/wsh/MyDbConnProperties.tsv
odbcprovider/src/test/resources/adodb/wsh/MyDbErr.tsv
odbcprovider/src/test/resources/adodb/wsh/MyDbTables.tsv

Improved error reporting in AdoDriver.
Added readonly mode in AdoDriver.
Added parsing of identifier case and string functions in AdoDriver.

Improved AdoDriver.

---

jtstoolkit/src/main/java/ec/tstoolkit/arima/ArimaModel.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/linearfilters/SymmetricFrequencyResponse.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/linearfilters/SymmetricFrequencyResponse2.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/linearfilters/SymmetricFrequencyResponseDecomposer2.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/linearfilters/SymmetricFrequencyResponseDecomposer3.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/polynomials/MullerNewtonSolver.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/polynomials/Polynomial.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/polynomials/SymmetricMullerNewtonSolver.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/polynomials/UnitRoots.java
jtstoolkit/src/test/java/ec/satoolkit/seats/WienerKolmogorovEstimatorTest.java
jtstoolkit/src/test/java/ec/tstoolkit/maths/linearfilters/SymmetricFrequencyResponse2Test.java
jtstoolkit/src/test/java/ec/tstoolkit/maths/polynomials/FunctionTest.java
jtstoolkit/src/test/java/ec/tstoolkit/maths/polynomials/SymmetricMullerNewtonSolverTest.java
jtstoolkit/src/test/java/ec/tstoolkit/ucarima/estimation/McElroyEstimatesTest.java

This improvement has a small impact on SEATS. The new factorization will allow the decomposition of high-frequency models

New factorization of the autocovariance function

---

jtstoolkit/src/main/java/ec/tstoolkit/timeseries/simplets/TsData.java

The method plus subtracted the double instead of adding it.

Corrected Bug in TsData

---

jtss/src/main/java/ec/tss/sa/SaItem.java

This allows the possibility to add comments on items of the SA multiprocessing.
Comments are added in the metadata of the item under the key `comment`

Comments on SaItems

---

jtss/src/main/java/ec/tss/formatters/CsvInformationFormatter.java
jtss/src/main/java/ec/tss/formatters/IStringFormatter.java
jtss/src/main/java/ec/tss/formatters/RegressionItemFormatter.java
jtss/src/main/java/ec/tss/formatters/StatisticalTestFormatter.java
jtss/src/main/java/ec/tss/sa/output/BasicConfiguration.java
jtss/src/main/java/ec/tss/sa/output/CsvOutput.java
jtss/src/main/java/ec/tss/sa/output/DefaultCollectionSummary.java
jtss/src/main/java/ec/tss/sa/output/SeriesSummary.java
jtss/src/test/java/ec/tss/sa/processors/X13ProcessorTest.java
jtstoolkit/src/main/java/ec/tstoolkit/algorithm/AlgorithmManager.java
jtstoolkit/src/main/java/ec/tstoolkit/arima/estimation/Forecasts.java
jtstoolkit/src/main/java/ec/tstoolkit/information/InformationSet.java
jtstoolkit/src/test/java/ec/tstoolkit/arima/estimation/ForecastsTest.java

The bug in forecasts appeared in case of missing values during the diffuse initialization of the Kalman filter

CSV formatters. Bug in CheckLast (Arima forecast)

---

jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/tramo/RegressionSpec.java
jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/x13/RegressionSpec.java
jtstoolkit/src/test/java/ec/tstoolkit/modelling/arima/tramo/RegressionSpecTest.java

- Added a method to set all fixed coefficients at once
- Fixed the string used as a key for outliers

Fixed regression coefficients

---

jtss/src/main/java/ec/tss/formatters/TableFormatter.java
jtss/src/main/java/ec/tss/tsproviders/utils/Formatters.java
jtss/src/main/java/ec/tss/tsproviders/utils/Params.java
jtss/src/main/java/ec/tss/tsproviders/utils/Parsers.java

- New formatters/parsers for `String[]`
- Improved `TableFormatter ` for arrays of objects

Formatters and parsers

---

jtstoolkit/src/main/java/ec/satoolkit/seats/KalmanEstimator.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/linearfilters/Utilities.java
jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/tramo/RegressionSpec.java
jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/x13/FinalEstimator.java
jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/x13/IGlsFinalEstimator.java
jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/x13/OutliersDetector.java
jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/x13/RegressionSpec.java
jtstoolkit/src/test/java/ec/tstoolkit/arima/estimation/ForecastsTest.java

Several small corrections (outliers, stock trading days, null parameters in Arima models...

Release 2.2.0

---

jtss/src/main/java/ec/demetra/xml/sa/tramoseats/TramoSeatsXmlProcessor.java
jtss/src/main/java/ec/demetra/xml/sa/tramoseats/XmlTramoRequests.java
jtss/src/main/java/ec/demetra/xml/sa/tramoseats/XmlTramoSeatsRequests.java
jtss/src/main/java/ec/demetra/xml/sa/x13/X13XmlProcessor.java
jtss/src/main/java/ec/demetra/xml/sa/x13/XmlRegArimaRequests.java
jtss/src/main/java/ec/demetra/xml/sa/x13/XmlX13Requests.java
jtss/src/test/java/ec/demetra/xml/sa/tramoseats/TramoSeatsXmlProcessorTest.java
jtstoolkit/src/main/java/ec/satoolkit/x11/X11Context.java
jtstoolkit/src/main/java/ec/tstoolkit/arima/ArimaModel.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/linearfilters/SymmetricFrequencyResponseDecomposer3.java
jtstoolkit/src/main/java/ec/tstoolkit/maths/polynomials/SymmetricMullerNewtonSolver.java

Corrections for xml requests, MA decomposition, Pseudo-add (partial)

Release 2.2.1

---

jdr/pom.xml
pom.xml
spreadsheetprovider/pom.xml
utilities/pom.xml

Updated dependencies.

---

jtstoolkit/src/main/java/ec/tstoolkit/timeseries/analysis/MovingProcessingFacade.java

Added the missing DoubleFormatter for ParameterInfo to fix NPE in Diagnostics -> Model stability -> Arima

Added missing formatter in MovingProcessingFacade

---

jtss/src/main/java/ec/tss/tsproviders/utils/Parsers.java
jtss/src/test/java/ec/tss/tsproviders/utils/DataFormatTest.java
jtss/src/test/java/ec/tss/tsproviders/utils/ParsersTest.java
sdmxprovider/src/main/java/ec/tss/tsproviders/sdmx/engine/TimeFormat.java

See https://www.ibm.com/developerworks/library/j-numberformat/index.html

Enforce strict parsing and formatting of dates and numbers

---

demetra-benchmarking/demetra-benchmarking-api/src/main/java/demetra/benchmarking/univariate/CubicSplineSpec.java
demetra-benchmarking/demetra-benchmarking-api/src/main/java/demetra/benchmarking/univariate/GrpSpec.java
demetra-benchmarking/demetra-benchmarking-core/src/main/java/jdplus/benchmarking/univariate/AggregationCubicSpline.java
demetra-benchmarking/demetra-benchmarking-core/src/main/java/jdplus/benchmarking/univariate/CubicSplineProcessor.java
demetra-benchmarking/demetra-benchmarking-core/src/test/java/jdplus/benchmarking/univariate/AggregationCubicSplineTest.java
demetra-benchmarking/demetra-benchmarking-r/src/test/java/demetra/benchmarking/r/BenchmarkingTest.java
demetra-toolkit/demetra-toolkit-core/demetra-toolkit-basic/src/main/java/jdplus/math/functions/CubicSpline.java
demetra-toolkit/demetra-toolkit-core/demetra-toolkit-basic/src/main/java/jdplus/math/functions/GenericCubicSpline.java
demetra-toolkit/demetra-toolkit-core/demetra-toolkit-basic/src/test/java/jdplus/math/functions/CubicSplineTest.java
demetra-toolkit/demetra-toolkit-core/demetra-toolkit-basic/src/test/java/jdplus/math/functions/GenericCubicSplineTest.java

Benchmarking

---

jtss/src/main/java/ec/tss/sa/SaProcessing.java
jtss/src/main/java/ec/tss/sa/processors/TramoSeatsProcessor.java
jtss/src/main/java/ec/tss/sa/processors/X13Processor.java
jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/tramo/RegressionSpec.java
jtstoolkit/src/main/java/ec/tstoolkit/modelling/arima/x13/RegressionSpec.java
jtstoolkit/src/main/java/ec/tstoolkit/timeseries/regression/InterventionVariable.java

New revision policy and fixed user-defined holidays. Bugs

Release 2.2.3
